name: SBOM
on:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions:
  security-events: write
  contents: write

jobs:
  dependency-graph:
    name: Update dependency graph
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Generate sarif
        uses: aquasecurity/trivy-action@0.34.1
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy.sarif.json'
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy.sarif.json'
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-24.04
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v6
      - name: Generate SBOM
        uses: aquasecurity/trivy-action@0.34.1
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'cyclonedx'
          output: 'nethsecurity-monitoring.cdx.json'
      - name: Upload SBOM
        env:
          GH_TOKEN: ${{ github.token }}
        run:
          gh release upload ${{ github.event.release.tag_name }} nethsecurity-monitoring.cdx.json
